apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edu-apps
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete. argocd를 사용할 것이어서 ns 바꾸면 안됨
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  # argocd 만들때 project 이름
  project: default
  
  source:
    repoURL: https://github.com/ujeongeom/app-of-apps-keycloak.git
    targetRevision: HEAD
    path: apps
  
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: default
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=false 
